### PR TITLE
Cholesky: Fix dgemm order in stream_df_cholesky, task creation in stream_df_cholesky_peek and force verification over the whole computed matrix

### PR DESCRIPTION
**Pull request by nmnobre**
Besides the fixes we have discussed, I've also enabled verification by default and over the whole matrix, so as to verify that the algorithm touched the correct matrix elements and those elements only.

### CODE REVIEW

**Comment by nmnobre** [comment]
Andi, also make sure to include the changes on commit 1ce1316 (Cholesky: Add missing matrix initialization to stream_df_cholesky_peek) you made on drebesium

**Comment by andidr** [comment]
> Andi, also make sure to include the changes on commit 1ce1316 (Cholesky: Add missing matrix initialization to stream_df_cholesky_peek) you made on drebesium

Done

**Comment by andidr** [comment]
Regarding the commit message and title: Please indicate in the commit message what has actually been changed. The title should be changed accordingly.

**Comment by andidr** [comment]
Thanks! Merged into master.

**Pull request closed without merging**
